version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  app:
    build:
      context: ./library_back
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db
