version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  back:
    build:
      context: ./library_back
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db
  front:
    build:
      context: ./library_front
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
