version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  test_front:
    working_directory: ~/trabalho-individual-gcs/library_front
    executor: node/default
    steps:
      - checkout:
          path: ~/trabalho-individual-gcs
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
  test_back:
    executor: python/default
    working_directory: ~/trabalho-individual-gcs/library_back
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout:
          path: ~/trabalho-individual-gcs
      - run: python3 main-test.py

workflows:
  test_my_app:
    jobs:
      - test_front
      - test_back
