version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    working_directory: ~/library_front
    executor: node/default
    steps:
      - checkout:
          path: ~/library_front
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests

workflows:
  test_my_app:
    jobs:
      - test
